### ISSUE TITLE
[Edit raster source band properties] allow expressions using counter variables to derive value lists

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#539]
_Requested by Sebastian van der Linden._

Add some useful counter variables like **bandNo** or **bandName** to derive property value lists.

E.g. for creating a list of band names running from **band 1** to **band n** use:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/9ae3b172-43de-4b33-8984-b788a63f0042)

Or to use the original band name plus the band number (e.g. to get rid of duplicated band names) use:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/e8e03d8f-d28d-4281-8c5b-340de5d52dc2)

More counter variables could be added later if needed.

**Comment by jakimowb** [comment]
Commit [7c024c0](https://github.com/EnMAP-Box/enmap-box/commit/7c024c052ad29bd7799ee56a6827edda395ddf4b) added

![grafik](https://github.com/EnMAP-Box/enmap-box/assets/1404870/f91930a5-d6a8-45a0-be37-19816d7edd2b)

Because it cannot be imported, hundres of unit tests fail https://github.com/EnMAP-Box/enmap-box/actions/runs/5831112406/job/15813854427

Any idea how to fix this @janzandr ?

**Comment by janzandr** [comment]
outdated
