### ISSUE TITLE
support temporal metadata provided by 'time' dimension in NetCDF files

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#906]
_Requested by @ffilipponi in #552 ..._

> I additionally suggest to automatically set Date Time reading 'time' dimension in NetCDF file, when available. It would significantly support time series analysis, especially for unevenly spaced time series.

**Comment by janzandr** [comment]
@ffilipponi, please provide a small NetCDF file for testing.

**Comment by ffilipponi** [comment]
@janzandr , please find two small samples of time series in NetCDF format:
- unevenly spaced time series
- evenly spaced time series
[NetCDF_time_series_samples.zip](https://github.com/user-attachments/files/15904078/NetCDF_time_series_samples.zip)

Please beware that units descriptor string of NetCDF time dimension may contain an origin. Here some examples:

time:units = "seconds since 1970-1-1"
time:units = "days since 1970-01-01 00:00:00"
time:units = "hours since 1990-11-25 12:00 UTC"

**Comment by janzandr** [comment]
Thanks for the datasets. Unfortunately, they don't seem to work in my QGIS:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/35aadf7a-d04f-4653-95e1-942d1b3e9f1f)

**Comment by ffilipponi** [comment]
@janzandr 
When importing spatially explicit NetCDF datasets in QGIS, you should only select the layers of interest having the chessboard pattern icon (thus excluding mesh and table icons). 
From the screenshot you provided I can not see what the danger icon refers to. CRS definition within NetCDF file it is sometimes not successfully read by QGIS. It can be set manually later in the layer properties.
In general, two QGIS user environment variables to effectively avoid many warnings and issues when importing NetCDF spatial datasets are:
IGNORE_XY_AXIS_NAME_CHECKS=YES
GDAL_NETCDF_BOTTOMUP=NO

**Comment by janzandr** [comment]
Strange, I downloaded your files again, and now ist's working :-)

**Comment by janzandr** [comment]
We already support the **NETCDF_DIM_time** format kind of, see #251. We just have to better support the different **time#units** values.
