### ISSUE TITLE
support temporal metadata provided by .aux.json files created with  R-cran terra package

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#907]
_Requested by @ffilipponi in #552 ..._

> Another source of datetime information associated to input raster data could be the found in .aux.json file generated when exporting raster data with explicit time dimension using R-cran terra package.

**Comment by janzandr** [comment]
@ffilipponi, please provide a small raster file created by _R-cran terra package_ for testing.

**Comment by ffilipponi** [comment]
@janzandr , please find two small samples of raster time series exported from _R-cran terra_ package in GeoTIFF format, complemented with '.aux.json' metadata containing time dimension information. _R-cran terra_ package exports by default '.aux.json' file when the _terra rast_ object to be exported has a defined time dimension (or other attributes).

[Unevenly_spaced_time_series_R-cran_terra.zip](https://github.com/user-attachments/files/15904135/Unevenly_spaced_time_series_R-cran_terra.zip)

Thanks for considering the new feature request

**Comment by janzandr** [comment]
Thanks. Looks like the format supports different units (i.e. timestep). For now I will implement the "days" unit used in your example:
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/b7836301-65dd-4ae6-9c9f-42cb69f44121)

If you need additional units, please provide some additional datasets (one for each unit).

**Comment by janzandr** [comment]
Done
![image](https://github.com/EnMAP-Box/enmap-box/assets/45030715/415fd053-bb5a-4d76-8255-e6991dd03a67)

**Comment by ffilipponi** [comment]
Thanks for implementing the feature.
Supported timesteps in _R-cran terra_ package are: 'seconds' (POSIXlt), 'days' (Date), 'yearmonths' (decimal years), 'years', 'months'. When the timestep is not defined, it will be exported as 'raw'. From my point of view, it might be sufficient to have only 'days' and 'seconds' supported in _EnMAP-Box_.
I forgot to specify that '.aux.json' file generated from _R-cran terra_ package may contain various keys, depending on the properties associated to the object of class _'rast'_ that is exported. As a consequence, the keys 'time' and 'timestep' required to set time axis in _EnMAP-Box_ may not always be defined in the '.aux.json' file. This needs an additional check to be integrated, in order to read time information only if it is defined in the '.aux.json' file. 
I suggest to modify line 787 in file 'rasterreader.py' as follows:

```
if self.terraMetadata is not None:
    if 'time' in self.terraMetadata.keys() and 'timestep' in self.terraMetadata.keys():
```
